### ISSUE TITLE
Can't provide multiple entries with output path in config file

### ISSUE THREAD

**Issue by victorronnow** [acss-io/webpack-atomizer-loader#23]
Current setup:

`index.html`
```html
<h1 class="C(red)">
    Hello, world!
</h1>
```

`about.html`
```html
<h1 class="C(blue)">
    About
</h1>
```

`webpack.config.js`
```js
let path = require('path');

module.exports = {
    entry: {
        mix: [
            './public/index.html',
            './public/about.html'
        ]
    },
    module: {
        rules: [
            {
                test: /\.(html)$/,
                use: {
                    loader: 'html-loader'
                }
            },
            {
                test: /\.(html)$/,
                exclude: /(node_modules)/,
                use: [
                    {
                        loader: 'webpack-atomizer-loader',
                        options: {
                            configPath: path.resolve('./acss.js')
                        }
                    }
                ]
            }
        ]
    }
}
```

`acss.js`
```js
module.exports = {
    cssDest: './resources/assets/sass/utilities.css'
}
```

`utilities.css`
```css
.C\(blue\) {
  color: blue;
}
```

`build/css/atomic.css` (without providing a config file)
```css
.C\(blue\) {
  color: blue;
}
.C\(red\) {
  color: red;
}
```

**Comment by redonkulus** [comment]
@victorronnow is still an issue? I'm confused on what the ask is.

**Comment by TonyBogdanov** [comment]
### The issue

@redonkulus Today I ran `npm update` in my project and started having the above issue. I think what @victorronnow is describing is that when you have two entry points, these are processed separately and thus the resulting classes are not merged, so you end up with only the classes from the most recently processed entry.

In my case this was not an apparent issue till today because my first entry does not contain any atomic classes.

After the update, however, for some reason the loader is now being invoked **multiple times**, i.e. for **each imported file**. This might be something specific to my setup, but nevertheless I think it's a good idea to be able to handle the scenario. The result is that atomizer extracts classes for each processed file, but *does not merge them*, and instead overwrites them. The final generated CSS file is being overwritten again and again and ends up empty in my particular case.

### Debugging

I've tested this with the latest webpack `5.50.0` and this function: https://github.com/acss-io/webpack-atomizer-loader/blob/master/lib/atomicLoader.ts#L98 is indeed called **for each imported file**.

I suppose the previous behavior was that all imports (for each webpack entry) were first resolved and collapsed before being passed to the loader in `source` in a single go.

### Proposal

For a very *quick-n-dirty* solution, since `configObject` is already global in your code: https://github.com/acss-io/webpack-atomizer-loader/blob/master/lib/atomicLoader.ts#L23 you could simply update its `classNames` with the ones atomizer generates so they will be available for merging in the next run:

```ts
// const cssString: string = atomizer.getCss(finalConfig, pathConfig.options || {});
pathConfig.configs.classNames = finalConfig.classNames;
```

I did test this and it works nicely in my particular case.

**Comment by redonkulus** [comment]
@dword-design Since you have been in the code lately, what are your thoughts on this feature enhancement? You are probably more familiar with the ins and outs of this part of the code at this point.

**Comment by dword-design** [comment]
@redonkulus This actually sounds like the issue I just fixed in [this PR](https://github.com/acss-io/webpack-atomizer-loader/pull/51). I've written details in the description.

**Comment by redonkulus** [comment]
Fixed by https://github.com/acss-io/webpack-atomizer-loader/pull/52
