### ISSUE TITLE
double compile

### ISSUE THREAD

**Issue by pot-code** [acss-io/webpack-atomizer-loader#29]
Hi, I'm using a customized webpack config, so I have to be very careful about compatibility.I have used expressjs as a compiler server, not sure if it caused the problem

This is my `atomic.js` configuration file:

```js
module.exports = {
  cssDest: './src/styles/atoms.css',
  configs: {
    breakPoints: {
      sm: '@media screen(min-width=357)',
      md: '@media(min-width=728px)',
      lg: '@media(min-width=1280px)'
    }
  },
  classNames: []
}
```

webpack config:

```js
{
  test: /\.tsx?$/,
  use: [
    {
      loader: 'webpack-atomizer-loader',
      options: {
        configPath: path.resolve(rootPath, 'atomic.js')
      }
    },
    {
      loader: 'babel-loader',
      options: {
        cacheDirectory: true
      }
    },
    {
      loader: 'ts-loader',
      options: { transpileOnly: true }
    }
  ],
  exclude: node_modules
},
{
  test: /\.less$/,
  include: srcPath,
  sideEffects: true,
  use: [
    {
      loader: 'css-loader',
      options: {
        modules: {
          context: srcPath,
          localIdentName: '[name]-[local]__[hash:base64:5]'
        },
        importLoaders: 2 
      }
    },
    postCSSLoader,
    'less-loader'
  ]
},
{
  test: /\.css$/,
  sideEffects: true,
  include: [...['normalize'].map(module => path.resolve(node_modules, module)), srcPath],
  use: ['css-loader', postCSSLoader]
}
```

Project structure:

```
src
  - style
    |-- index.css
    |-- atoms.css(generated)
    index.tsx
```

Import code:

```css
/* index.css */
@import './atoms.css';
```

Until the webpack dev server serves the content in memory, I haven't found a way to inject the generated CSS into the server, so I chose to redirect the CSS file to my source folder to expose it, or the compiler would complain that it can not resolve `atoms.css`.

When I start my dev server, it will compile twice, the first one for initial compile, and the second one is triggered by generated CSS, this will cause a flash experience in browser. When I try to build the project, I have to build it twice to generate correct CSS

There must be some race conditions, any ideas? thanks!

**Comment by AntonioRedondo** [comment]
Probably you already saw this warning message on `README.md`:
![image](https://user-images.githubusercontent.com/5444421/128270757-f74d7c7a-0ecd-44f2-bbaf-561894b81d35.png)

The reason why a double compilation is needed is because, as you well point, there is a race condition between the CSS generated by the `webpack-atomizer-loader` and the `css-loader` that is expecting the CSS file generated by the `webpack-atomizer-loader`. The CSS file with the atoms isn't always generated by the time `css-loader` is trying to import it.

Unlike in [Gulp](https://gulpjs.com) and its [`series()`](https://gulpjs.com/docs/en/api/series) and [`parallel()`](https://gulpjs.com/docs/en/api/parallel) methods, there is no way in webpack of waiting for a loader to start working another one. They all start in parallel.

If you want to prevent this race condition, instead of importing the CSS file with:
```css
/* index.css */
@import './atoms.css';
```
do it in the top HTML file importing JavaScript and CSS files:
```html
<!-- public/index.html -->
<html>
  <head>
    <link href="atoms.css" rel="stylesheet" type="text/css" /> <!-- Add this line -->
  </head>
```
